[package]
name = "faces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.2"
cached = "0.26.2"
env_logger = "0.9.0"
serde = "1.0.130"
slack_api = "0.23.1"
